name: Run tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
    types: [opened, synchronize, reopened]

jobs:
  test:
    if: startsWith(github.head_ref, 'features/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest

