name: Run tests on pull request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    if: startsWith(github.head_ref, 'features/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install nox
        run: pip install nox
      - name: Run tests
        run: nox
